apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemon
  labels:
    app: green
spec:
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: example-container
        image: httpd
        # Add any additional container settings here
