apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
   color: black 
spec:
  replicas: 10 
  selector:
    matchLabels:
      color: black
  template:
    metadata:
      labels:
        color: black
    spec:
      containers:
        name: mycont.
      - image: httpd 
        ports:
        - containerPort: 80
