apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  color: black 
spec:
  selector:
    matchLabels:
      color: black
  template:
    metadata:
      labels:
        color: black
    spec:
      containers:
      - name: mycont.
        image: httpd 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
