apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   color: black 
  name: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      color: black
  template:
    metadata:
      labels:
        color: black
    spec:
      containers:
      - image: httpd
        name: mycont
        ports:
        - containerPort: 80
