apiVersion: v1
kind: Pod
metadata:
  name: gaurpod
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: httpd
    ports:
     - containerPort: 80
    volumeMounts:
      - mountPath: /var/www/html/
        name: new-pvc
  volumes:
    - name: new-pvc
      persistentVolumeClaim:
      claimName: merafirstpvc
