apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: black 
spec:
  imagepullserects: mgcred
  containers:
  - name: myapp
    image: mohitgaur1272/ap2
    ports:
      - containerPort: 80
