apiVersion: v1
kind: PersistentVolume
metadata:
  name: mohitpv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast
  hostPath:
    path: /data/mohit 