apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 4
  template:
    metadata: 
      labels:
        name: abc
    spec:
      containers:
        - name: mycont
          image: httpd 
          ports:
            - containerPort: 80 
